sudo: required
language: java
dist: trusty
services:
  - 'docker'

addons:
  sonarcloud:
    organization: "diegotony" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN  # encrypted value of your token
script:
  - sonar-scanner

before_install:
  - 'chmod +x .travis/main.sh'
  - './.travis/main.sh'

script:
  - 'make test'
  - 'make image'



after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

# don't notify me when things fail

notifications:
  email: false